<a href="https://colab.research.google.com/github/srikant-ai/Deep_Learning_TensforFlow/blob/main/Deep_learning_%26_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introdcution to `TensorFlow`

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


### Create tensors with `tf.constant()`

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [4]:
# Create a vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimension of the vector 
vector.ndim

1

In [6]:
# Create a Matrix
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# check the dimension of matrix
matrix.ndim

2

In [8]:
# Create another matrix 
another_matrix= tf.constant([[10.,7.],
                             [3.,2,],
                             [8.,9.]], dtype= tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# check the dimension of another_matrix
another_matrix.ndim

2

In [10]:
# Let's create a tensor 
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
# check the dimension of tensor
tensor.ndim

3

What we've created so far:

1. Scalar : a single number
2. Vector : a number with direction (e.g wind speed and direction)
3. Matrix : a 2-dimsional array of numbers
4. Tensor : a n-dimensional array of numbers (where n can be any number)

### Create tensors using `tf.variable()`

In [12]:
# create the same tensor with tf.Varaible() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Lets try chnaging one of the elements in our changeable tensor
changeable_tensor[0] = 7

TypeError: ignored

In [14]:
# How about we try .assign() 
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# Lets try chnaging one of the elements in our unchangeable tensor
unchangeable_tensor[0].assign(7)
cunhangeable_tensor

AttributeError: ignored

### Creating random tensor using `tf.random`

Random tensors are tensors of some arbitary size which contain random numbers.

`tf.random.uniform()` gives tensors from a uniform distribution (equal probability over a given range for a continuous distribution)

In [ ]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = tf.random.uniform(shape=(3,2))
random_1

`tf.random.normal()` gives tensors from a normal distribution (is a probability distribution that is symmetric about the mean, showing that data near the mean are more frequent in occurrence than data far from the mean)

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))

In [ ]:
random_1

In [16]:
random_2

NameError: ignored

In [17]:
# Are they equal ?
random_1 == random_2 

NameError: ignored

### shuffle the order of elements in a tensor

In [ ]:
# shuffle a tensor (comes handy whe we want to shuffle data so the inherent order doesn't affect the learning)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim

In [ ]:
tf.random.shuffle(not_shuffled, seed=None)

In [ ]:
# with seed
tf.random.set_seed(42) # global level seed
tf.random.shuffle(not_shuffled, seed=42) # operation leve seed

### Other ways to Create tensors

In [ ]:
# Create a tensor of all ones
tf.ones([10,7])

In [ ]:
# Create a trnsor of al zeros
tf.zeros([10,7])

### Turn Numpy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run a GPU (much faster for numerical computing)

In [18]:
# You can also turn NumPy into tensors
import numpy as np
numpy_A= np.arange(1,25 , dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [19]:
A=tf.constant(numpy_A, shape=(2,3,4))
B=tf.constant(numpy_A)
A , B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting more information `(attributes)` from tensors

* Shape : `tensor.shape`
* Rank  : `tensor.ndim`
* Axis  : `tensor[0], tensor[:,1]....`
* Size  : `tf.size(tensor)`

In [20]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [21]:
# Shape of of the tensor
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [22]:
# Rank/Dimension of tensor
rank_4_tensor.ndim  

4

In [23]:
# Axis based tensor representation
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [24]:
# size of the tensor
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

### Matrix Multiplication

In [25]:
#matrix multiplication in tensorflow
tensor =tf.constant([[10,7],
                     [3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [26]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [27]:
# muliplication in python with "*" operator
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [28]:
# muliplication in python with "@" operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [29]:
# create a tensor with shape (3,2)
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])


In [30]:
# Try to multiply tensors of shape 
X @ Y

InvalidArgumentError: ignored

In [ ]:
tf.matmul(X,Y)

#### Rules to Multiply 2 tensors:

* Rule 1 : Inner Dimensions of the Matrix must match.
* Rule 2 : The Resulting Matrix has the shape of the outer dimensions.

In [31]:
# Lets change the shape of Y
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [32]:
# Try to Multiply X with Reshaped Y
tf.matmul(X,tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [34]:
# perform the dot product on X and Y 
tf.tensordot(tf.transpose(X),Y,axes =1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [1]:
import tensorflow as tf

In [3]:
!nvidia-smi

Sun Jul 18 13:14:25 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------